### PR TITLE
Change deprecated zip functions

### PR DESCRIPTION
**Pull request by MDylan**

### CODE REVIEW

**Comment by Mo7mud** [comment]
It seems the repo is no longer maintained unfortunately.

**Comment by Mo7mud** [comment]
If you have time please open issues section in your fork so we can post issues there and work on it.
Thank you

**Comment by MDylan** [comment]
> If you have time please open issues section in your fork so we can post issues there and work on it. Thank you

Ok I have done this. I have some new ideas with it.

**Comment by Mo7mud** [comment]
> > If you have time please open issues section in your fork so we can post issues there and work on it. Thank you
> 
> Ok I have done this. I have some new ideas with it.

Me too
I'll contribute my changes to your fork, I've done some already

**Pull request closed without merging**
