### PR TITLE
Features: Add support for upgrading through the artisan command

### PR DESCRIPTION
**Pull request by mohamad-supangat**
My reference comes from Nextcloud which provides update commands through the console, like this: 
```fish
www@localhost /v/s/w/n/html> php-legacy occ upgrade
Nextcloud is already latest version

```

my target is:

- [x] Separates the main function of Laraupdater, which was controlled into the helper file, so that it can use it repeatedly
- [x] Console Command to get the current version
- [x] Console Command to get the latest version of the server
- [x] Console Command to update application
- [x] Make sure the web controller functions well using the function of the helper

### CODE REVIEW

**Comment by mohamad-supangat** [comment]
image

**Comment by mohamad-supangat** [comment]
The function runs perfectly in the console 😎

Ignore the Log Display, I haven't found a way to beautify the appearance 🤪

image

**Comment by mohamad-supangat** [comment]
Great now the route complete work

image

**Comment by pietrocinaglia** [comment]
Great. Thanks so much for your intuition and implementation.

**Pull request merged**
